title: I'm already a developer
email: yukihirai0505@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yuki Hirai
baseurl: ""
url: "https://yukihirai0505.github.io"
twitter_username: yukihirai0505
github_username:  yukihirai0505

markdown: kramdown
theme: minima
gems:
  - jekyll-gist
  - jekyll-paginate
paginate: 10
paginate_path: "/page/:num"
